apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app-container
          image: testandovisse/hello-app:775ebfee4dec11fde685ca2740eee165d7143f39
          ports:
            - containerPort: 8000
      imagePullSecrets:
      - name: regcred
