apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app-container
          image: IgorMacdo/hello-app:0cce2eef8f4fd97247e880c41aa11bbcb6b8aafb
          ports:
            - containerPort: 8000
      imagePullSecrets:
      - name: regcred
